title: Gary White # your name (or website title) here
logo: "Desktop/20220206_175921.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Senior GIS Analyst at JSJ7 where I am responsible for creating 3D terrain-based simulations for the military to train with.
  <br><br>
  Huntington Ingalls
  <br><br>
  Suffolk, VA
  <br><br>
  <a href="https://www.linkedin.com/in/gary-white-4412a951">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
